base_url = "https://aussie.tax"
title = "Australian Tax Calculator"
description = "Compare new Aussie tax cut schemes. Calculate your tax cut and see how much you will save next year. See how much better or worse off you are with the new scheme compared to the previous cancelled proposal."
default_language = "en"
build_search_index = false
compile_scss = true
compile_sass = true
minify_html = false

[extra]
author = "Posnet"
email = "aussie-tax@denialof.services"
image = "https://aussie.tax/tax_cut_share.png"

[markdown]
highlight_code = true

[build]
sitemap = "sitemap.xml"
